### ISSUE TITLE
14 markers, but 12 joints?

### ISSUE THREAD

**Issue by antithing** [oscarwestberg/Face-Tracking-Maya#2]
Hi! Thank you for making this code available. I have it running, but the data in maya looks scrambled. Looking into the code, it seems to expect 14 markers in the c++, but maya expects 12.

FOREHEAD and NOSE are missing in maya. 

I have changed 

`MARKER_COUNT = 12`

and commented out the NOSE and FOREHEAD, but the data still looks crazy.

Are you able to upload the rig with 14 joints, if you have time?

Or point me at the changes to get back to twelve markers in the cpp?

Thank you again!

**Comment by oscarwestberg** [comment]
Hello! It's supposed to be 14 markers and I'm afraid that rig is the only one I have available. It was some time since I worked with this and can't remember if we had any issues with the marker amount. Here's how it's supposed to look: https://youtu.be/UXrC1aBjDrM

**Comment by AronTornberg** [comment]
The nose and forehead markers are just used to track head angle/position if I remember correctly.

Honestly, our code has lots of problems. It's probably better to use it as inspiration for your own implementation.

**Comment by oscarwestberg** [comment]
True that

**Comment by antithing** [comment]
Thanks guys! I ended up writing my own functions, but definitely used your stuff for reference, so many thanks!

**Comment by oscarwestberg** [comment]
Nice! Good luck with your project!
